"""empty message

Revision ID: aeb4403467ca
Revises: c108664db6d1
Create Date: 2025-06-10 02:30:47.706700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb4403467ca'
down_revision = 'c108664db6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_peoples', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_fav_people', ['user_id', 'peoples_id'])

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_fav_planet', ['user_id', 'planets_id'])

    with op.batch_alter_table('favorite_starships', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_fav_starship', ['user_id', 'starships_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_starships', schema=None) as batch_op:
        batch_op.drop_constraint('unique_fav_starship', type_='unique')

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_fav_planet', type_='unique')

    with op.batch_alter_table('favorite_peoples', schema=None) as batch_op:
        batch_op.drop_constraint('unique_fav_people', type_='unique')

    # ### end Alembic commands ###
